Fix success snackbar for Vendors and Products in settings (#415)
humansis/front pull request #416
Opened 2020-10-23 12:12 UTC by jakubdvorak-g

2020-10-23 12:22 UTC, jakubdvorak-g commented
@blazekv please code rew

2020-10-23 12:28 UTC, blazekv requested changes

2020-10-23 12:28 UTC, blazekv commented on src/app/core/utils/modal.service.ts
> +              result = 'Vendor'
This will work only for english.

2020-10-26 14:12 UTC, jakubdvorak-g commented
Final solution is done. After consultation we give away title from success snackbar. Please code review again @blazekv

2020-10-27 08:27 UTC, blazekv approved these changes

2020-11-11 15:07 UTC, merged